version: '3'

services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/code
    ports:
      - 5000:5000
    environment:
      - PORT=5000